# Generated by Django 2.1.1 on 2018-09-15 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=50)),
                ('audio', models.FileField(upload_to='uploads/')),
                ('script', models.FileField(upload_to='uploads/')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
