# Generated by Django 2.1.1 on 2018-09-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0002_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='name',
            field=models.CharField(default='meeting', max_length=50),
        ),
    ]
