# Generated by Django 2.1.1 on 2018-09-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0003_meeting_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='id',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='null', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='client',
            name='nickName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='sessionid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='user_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
