# Generated by Django 2.1.1 on 2018-09-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0004_auto_20180922_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nickName',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
