# Generated by Django 2.1.1 on 2018-10-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0005_auto_20180922_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='audio',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='script',
            field=models.FileField(max_length=5000000, null=True, upload_to=''),
        ),
    ]
