# Generated by Django 2.1.1 on 2018-10-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0006_auto_20181006_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='script',
            field=models.CharField(max_length=5000000000, null=True),
        ),
    ]
