# Generated by Django 2.1.1 on 2018-10-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0007_auto_20181006_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='sessionid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
